# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/surfml',
                'doc_host': 'https://coderbee.github.io',
                'git_url': 'https://github.com/coderbee/surfml',
                'lib_path': 'surfml'},
  'syms': {'surfml.core': {'surfml.core.foo': ('core.html#foo', 'surfml/core.py')}}}